// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvX0smEO_31nb9ZpjMCYNdiOppuVUQhSI',
    appId: '1:569195124600:web:19e8e60205624e217fda8d',
    messagingSenderId: '569195124600',
    projectId: 'security-key-4f9fb',
    authDomain: 'security-key-4f9fb.firebaseapp.com',
    storageBucket: 'security-key-4f9fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTilOxMs0P9JDRVmulzbNZDVimrNArCE',
    appId: '1:569195124600:android:0b6140a0a5ccf40f7fda8d',
    messagingSenderId: '569195124600',
    projectId: 'security-key-4f9fb',
    storageBucket: 'security-key-4f9fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNtaoqq-Z_NWLhZvFl5Fcxv6cPfBFFLf0',
    appId: '1:569195124600:ios:4e55519e88be12157fda8d',
    messagingSenderId: '569195124600',
    projectId: 'security-key-4f9fb',
    storageBucket: 'security-key-4f9fb.firebasestorage.app',
    iosBundleId: 'com.example.securitykey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtaoqq-Z_NWLhZvFl5Fcxv6cPfBFFLf0',
    appId: '1:569195124600:ios:4e55519e88be12157fda8d',
    messagingSenderId: '569195124600',
    projectId: 'security-key-4f9fb',
    storageBucket: 'security-key-4f9fb.firebasestorage.app',
    iosBundleId: 'com.example.securitykey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvX0smEO_31nb9ZpjMCYNdiOppuVUQhSI',
    appId: '1:569195124600:web:52ee9ff63b1883227fda8d',
    messagingSenderId: '569195124600',
    projectId: 'security-key-4f9fb',
    authDomain: 'security-key-4f9fb.firebaseapp.com',
    storageBucket: 'security-key-4f9fb.firebasestorage.app',
  );
}
